# PRODUCT DATA
- product_id: 1
  product_name: "Python and Flask Bootcamp Create Websites using Flask!"
  product_sort_desc: "Create awesome websites using the powerful Flask framework for Python!"
  product_desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum"
  product_price: 129
  product_buy_url: "https://www.udemy.com/course/python-and-flask-bootcamp-create-websites-using-flask/"
  product_img: ""

- product_id: 2
  product_name: "React - The Complete Guide (incl Hooks, React Router, Redux)"
  product_sort_desc: "Dive in and learn React.js from scratch! Learn Reactjs, Hooks, Redux, React Routing, Animations, Next.js and way more!"
  product_desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum"
  product_price: 109
  product_buy_url: "https://www.udemy.com/course/react-the-complete-guide-incl-redux/"
  product_img: ''

- product_id: 3
  product_name: 'Node with React: Fullstack Web Development'
  product_sort_desc: "Build and deploy fullstack web apps with NodeJS, React, Redux, Express, and MongoDB."
  product_desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum"
  product_price: 119
  product_buy_url: 'https://www.udemy.com/course/node-with-react-fullstack-web-development/'
  product_img: ''

- product_id: 4
  product_name: 'React Native - The Practical Guide 2020'
  product_sort_desc: "Use React Native and your React knowledge and take your web development skills to build native iOS and Android Apps."
  product_desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum"
  product_price: 149
  product_buy_url: 'https://www.udemy.com/course/react-native-the-practical-guide/'
  product_img: ''

- product_id: 5
  product_name: "Docker Mastery: with Kubernetes +Swarm from a Docker Captain"
  product_sort_desc: "Build, test, deploy containers with the best mega-course on Docker, Kubernetes, Compose, Swarm and Registry using DevOps"
  product_desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum"
  product_price: 145
  product_buy_url: 'https://www.udemy.com/course/docker-mastery/'
  product_img: ''
